### PR TITLE
MINIFI-418: Added docs on Windows service for 64bit machine

### PR DESCRIPTION
**Pull request by ijokarumawak**
Thank you for submitting a contribution to Apache NiFi - MiNiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi-minifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under minifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under minifi-assembly?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jzonthemtn** [comment]
Would it be better to just use the 64bit version instead and change your documentation to be for 32bit? I'm guessing users might want 64bit version more often anyway.

**Comment by ijokarumawak** [comment]
@jzonthemtn Hmm, I'm not sure, because the PR has been confirmed by at least two people and both didn't encounter issue.

I've tested it again. Even if on 64bit machine, if JDK (or JRE) for 32bit is installed the 32bit minifi.exe works. It didn't work before because I had only 64bit JDK.

**Comment by ijokarumawak** [comment]
@jzonthemtn looking at more articles on current situation of 32 bit and 64 bit share, I'd prefer to go with 64 bit as default. Added another commit to make 64 bit as default. Does it look reasonable?

**Comment by apiri** [comment]
yeah, 64 bit makes more sense at this stage.  As @ijokarumawak pointed out on the JIRA ticket, it seems that if a user has a 32-bit JRE installed, they would not experience issues.  The machine in particular that I was doing verification on seemed to have both 32 and 64 bit (presumably from some other application installed on the machine).  Anyway, this makes more sense to me.

**Comment by apiri** [comment]
@ijokarumawak This was merged in 03aceefce523d3b957ee18c5fb1a595241dddc4d but I forgot to add the closing line.  Would you please be able to close this issue when you have the opportunity?

**Pull request closed without merging**
