### PR TITLE
MINIFI-154 Adding support for Controller Services

### PR DESCRIPTION
**Pull request by JPercivall**

### CODE REVIEW

**Comment by brosander** [comment]
Reviewing

**Comment by brosander** [comment]
@JPercivall I'm having trouble using the StandardHttpContextMap with an exported template with 2 process groups.

[HttpContextMapTest.xml](https://blog.rosander.ninja/attachments/random/2016/12/08/HttpContextMapTest.xml)

Transform:
```
Found the following duplicate controller service ids: dfd99469-0158-1000-0000-000000000000
```

Runtime:
```
Exception in thread "main" java.io.IOException: Unable to successfully transform the provided configuration
        at org.apache.nifi.minifi.bootstrap.RunMiNiFi.performTransformation(RunMiNiFi.java:1706)
        at org.apache.nifi.minifi.bootstrap.RunMiNiFi.start(RunMiNiFi.java:1183)
        at org.apache.nifi.minifi.bootstrap.RunMiNiFi.main(RunMiNiFi.java:244)
Caused by: org.apache.nifi.minifi.bootstrap.exception.InvalidConfigurationException: Failed to transform config file due to:[Found the following duplicate controller service ids: dfd99469-0158-1000-0000-000000000000]
        at org.apache.nifi.minifi.bootstrap.util.ConfigTransformer.throwIfInvalid(ConfigTransformer.java:114)
        at org.apache.nifi.minifi.bootstrap.util.ConfigTransformer.transformConfigFile(ConfigTransformer.java:98)
        at org.apache.nifi.minifi.bootstrap.RunMiNiFi.performTransformation(RunMiNiFi.java:1700)
        ... 2 more
```

**Comment by brosander** [comment]
I'm getting the following error indicating the flow.xml.gz output by the ConfigTransformer doesn't validate against [FlowConfiguration.xsd](https://github.com/apache/nifi/blob/rel/nifi-1.1.0/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/resources/FlowConfiguration.xsd)

```
2016-12-08 19:39:30,448 ERROR [MiNiFi logging handler] org.apache.nifi.minifi.StdErr [Error] :220:17: cvc-complex-type.2.4.a: Invalid content was found starting with element 'connection'. One of '{controllerService}' is expected.
2016-12-08 19:39:30,483 ERROR [MiNiFi logging handler] org.apache.nifi.minifi.StdErr [Error] :220:17: cvc-complex-type.2.4.a: Invalid content was found starting with element 'connection'. One of '{controllerService}' is expected.
2016-12-08 19:39:30,496 ERROR [MiNiFi logging handler] org.apache.nifi.minifi.StdErr [Error] :220:17: cvc-complex-type.2.4.a: Invalid content was found starting with element 'connection'. One of '{controllerService}' is expected.
2016-12-08 19:39:30,511 ERROR [MiNiFi logging handler] org.apache.nifi.minifi.StdErr [Error] :220:17: cvc-complex-type.2.4.a: Invalid content was found starting with element 'connection'. One of '{controllerService}' is expected.
2016-12-08 19:39:30,546 ERROR [MiNiFi logging handler] org.apache.nifi.minifi.StdErr [Error] :220:17: cvc-complex-type.2.4.a: Invalid content was found starting with element 'connection'. One of '{controllerService}' is expected.
2016-12-08 19:39:30,564 ERROR [MiNiFi logging handler] org.apache.nifi.minifi.StdErr [Error] :220:17: cvc-complex-type.2.4.a: Invalid content was found starting with element 'connection'. One of '{controllerService}' is expected.
```

**Comment by JPercivall** [comment]
@brosander the template issue you ran into is related to a bug in NiFi 1.1.0 template generation, which NIFI-3129[1] was created for. It has since been resolved.

That said, I ran into your issue in a slightly different way on the latest master and I've created a ticket for it here[2]

[1] https://issues.apache.org/jira/browse/NIFI-3129
[2] https://issues.apache.org/jira/browse/NIFI-3173

**Comment by JPercivall** [comment]
@brosander I just pushed out a new commit addressing the xsd issues.

**Comment by brosander** [comment]
+1 Merging

**Pull request closed without merging**
