### PR TITLE
MINIFI-127: Added quick start document.

### PR DESCRIPTION
**Pull request by thesolson**
Thank you for submitting a contribution to Apache NiFi - MiNiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:
### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
   in the commit message?
- [ ] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [ ] Is your initial contribution a single, squashed commit?
### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi-minifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under minifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under minifi-assembly?
### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?
### Note:

Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by brosander** [comment]
@thesolson it looks like there need to be some newlines in [this section](https://github.com/thesolson/nifi-minifi/blob/MINIFI-127/minifi-docs/src/main/markdown/minifi-java-agent-quick-start.md#for-linux-and-mac-os-x-users) to make the numbered lists appear properly.

I think I usually do a newline before and after the list.

**Comment by apiri** [comment]
hey @thesolson,

got to scope this out and overall looks good.  some folks also had some additional commentary for some minor fixes, but otherwise looks like a great start and will certainly be helpful for getting people going down the appropriate path

**Comment by JPercivall** [comment]
@apiri @thesolson I created a patch addressing the feedback that was left. Just rename it from ".txt" to ".patch" to apply it.

[0001-MINIFI-127-In-quick-start-guide-removing-processors-.txt](https://github.com/apache/nifi-minifi/files/622464/0001-MINIFI-127-In-quick-start-guide-removing-processors-.txt)

**Comment by thesolson** [comment]
@apiri I've applied Joe's patch. The changes look great! Please feel free to finalize the review and merge if appropriate.

**Comment by apiri** [comment]
@thesolson & @JPercivall,

Thanks for the updates/patches.  Looks good here and will get this merged in.

**Pull request closed without merging**
