### PR TITLE
MINIFI-272 - Delegating C2 Provider, Caching ConfigService, Tests

### PR DESCRIPTION
**Pull request by brosander**
Thank you for submitting a contribution to Apache NiFi - MiNiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi-minifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] - N/A - If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [X] - N/A - If applicable, have you updated the LICENSE file, including the main LICENSE file under minifi-assembly?
- [X] - N/A - If applicable, have you updated the NOTICE file, including the main NOTICE file found under minifi-assembly?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by apiri** [comment]
reviewing

**Comment by apiri** [comment]
hey @brosander,

been playing around with this for a while now and it is an awesome set of code and tests.  would you mind folding in the image on the issue into docs some place?  not necessarily in the root README but perhaps either in the root of the c2 project or the c2-assembly.  If you think we'll need to do a lot of iteration as we go through, could also just link out to a space on the minifi wiki.

otherwise, code looks good and the tests are super awesome.

**Comment by brosander** [comment]
@apiri added a readme, please let me know if that's what you were thinking about.

**Comment by apiri** [comment]
Thanks for adding those on and is a great start.  Will get this merged.

**Pull request closed without merging**
