### PR TITLE
MINIFI-438 Refactor MiNiFi C2 Server

### PR DESCRIPTION
**Pull request by kevdoran**
This begins refactoring MiNiFi C2 Server to lay the groundwork for future commits that will add new functionality, specifically, NiFi Registry integration as the prefered method of deploying flows to agents.

The primary goals  of this refactor include:

- Align the C2 server dependencies with those used by NiFi Registry,
    so that we are using the same versions of libraries such as Jersey
    and Jackson. This will allow us to easily integrate the Java
    nifi-registry-client module into C2 server.
- Reuse patterns and best practices established by the NiFi Registry
    project, so that one day more code can be extracted and shared across
    web services in the NiFi ecosystem (for example, the security
    framework), with a secondary benefit being developers working on both
    projects will only have to learn one set of frameworks and patterns.

Thank you for submitting a contribution to Apache NiFi - MiNiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi-minifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under minifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under minifi-assembly?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by apiri** [comment]
reviewing

**Comment by kevdoran** [comment]
Yes, L&N needs to be updated to include new dependencies that have been bundled: Spring Boot, Flyway, etc. I was originally thinking about doing a final audit of L&N prior to merging this feature branch into master, but as we'll likely want to preserve the history of this long-lived branch it will probably be better to have the L&N changes in each commit that adds/removes dependencies.

I'll remove the commented code/dependencies. Some may come back when I get to adding back the functionality that has been temporarily removed in order to make some framework changes, but I'll add them back as necessary in future commits. The current, commented dependencies as part of this commit was unintentional, thanks for spotting.

**Comment by kevdoran** [comment]
@apiri I cleaned up some of the dependencies that have changed and made the corresponding LICENSE and NOTICE changes. Please let me know if you see anything else to address in this PR. Thanks!

**Comment by apiri** [comment]
Looks good to me.  I merged this to the working branch but GitHub won't automatically close it because it's not master.  Please feel free to close this at your convenience.

**Pull request closed without merging**
