### PR TITLE
MINIFI-424: Centralise Bootstrap config

### PR DESCRIPTION
**Pull request by GCHQ-NiFi**
I've consolidated the bootstrap transformation code into a new BootstrapTransformation class, and simplified the transformConfigFile function to accept bootstrap properties instead of individual schemas.

This should allow for simpler config overwriting in the future (currently supports SSL and provenance reporting).

I've piggybacked on an existing ticket that references similar changes - but am happy to raise a new one if needed!

Thank you for submitting a contribution to Apache NiFi - MiNiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi-minifi folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file under minifi-assembly?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found under minifi-assembly?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by GCHQ-NiFi** [comment]
@apiri Do you mind reviewing and seeing whether this is a better way of managing config transformation? Happy to make changes as needed!
Going forward, we have other ideas which could take advantage of this - like passing in a boolean through the bootstrap.conf to hard code all processor SSL-Contexts to the minifi SSL config set in the bootstrap. We've had problems using SSL contexts when driving minifi with c2. As the nifi uses it's own SSL, this gets pulled across into minifi - which points to the wrong SSL details and can't start.

**Comment by gruselglatz** [comment]
@GCHQ-NiFi Does this fix the issue, that Minifi cant connect via SSL to Nifi when Minifi-C2 is used?

bootstrap.conf doesnt overwrite ssl settings in config.yml as intended, and every time C2 is refreshing the config, ssl wont connect anymore (because empty)

**Comment by GCHQ-NiFi** [comment]
@gruselglatz - No, this pull request just simplifies the transformConfigFile function.
If this is merged in, it'll be easier to override flow settings using the bootstrap.conf (like the C2 SSL override). I've got a fix for the C2 SSL ready to go, it just relies on this pull request to get merged in first.

**Comment by gruselglatz** [comment]
@GCHQ-NiFi Oh I understand, so do you have a hint for me, how i can use C2 and connect via SSL?

Or do you have a Branch which i can Build to fix this problem?
Thx

**Comment by apiri** [comment]
@GCHQ-NiFi hey there, I've been away from work for some family stuff but will scope this out in the near future.

**Comment by apiri** [comment]
reviewing

**Pull request closed without merging**
