### PR TITLE
MINIFI-276: Adds S3ChangeIngestor.

### PR DESCRIPTION
**Pull request by jzonthemtn**
Thank you for submitting a contribution to Apache NiFi - MiNiFi.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with MINIFI-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

- [X] Is your initial contribution a single, squashed commit?

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via mvn -Pcontrib-check clean install at the root nifi-minifi folder?
- [X] Have you written or updated unit tests to verify your changes?
- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [] If applicable, have you updated the LICENSE file, including the main LICENSE file under minifi-assembly?
- [X] If applicable, have you updated the NOTICE file, including the main NOTICE file found under minifi-assembly?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by jzonthemtn** [comment]
I tested this by having the local config.yml be the same as the one on S3. I started MiNiFi. Then I uploaded a modified config.yml and at the next interval check the new config was found and MiNiFi reloaded with its config. I watched a bit to make sure the ETag check worked as expected when determining if the config had changed. I had a JUnit integration test that used a local S3 simulator but decided it was too clunky and removed it.

**Comment by brosander** [comment]
I think an S3 ingestor would be really useful.  I'm a little worried though about longer term implications of adding more ingestors that each have their own dependencies to the bootstrap directory.

I wonder if now would be a good time to try to sort out a good way to let users drop in an ingestor implementation they'd like to use without requiring everyone to have the new dependencies in their minifi install.

Maybe something like the nar format for NiFi would make sense here.  Or maybe just a zip archive that can be unzipped into the bootstrap directory during install of MiNiFi.

**Comment by jzonthemtn** [comment]
I will volunteer to write this up as a [MiNiFi Feature Proposal](https://cwiki.apache.org/confluence/display/MINIFI/MiNiFi+Feature+Proposals) to take the discussion there but I don't seem to be able to create a page on that space.

**Comment by brosander** [comment]
@apiri what is the process @jzonthemtn can use to get a feature proposal on wiki?

**Comment by apiri** [comment]
hey @jzonthemtn and @brosander,

permission are not straightforward with the wiki spaces (or I haven't figured out how to better tie them together) but I have added you to be an editor (jzemerick).  Please let me know if there are any issues and I'll be happy to assist further.

Thanks!

**Comment by jzonthemtn** [comment]
I think this might be better as an implementation of `ConfigurationProvider` in C2. That way configurations can be stored on S3 but MiNiFi's small footprint can be preserved. Would that work better?

**Comment by jzonthemtn** [comment]
I'm going to go ahead and close this because I do think the functionality would be better in C2 instead of adding avoidable bloat to MiNiFi.

**Pull request closed without merging**
